blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions / ����������
    url: https://github.com/11suixing11/mindnotes-pro/discussions
    about: Ask questions or start a discussion here / ���ڴ˴����ʻ�������
